/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Student;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class DetaljiForma extends javax.swing.JFrame {

    /**
     * Creates new form DetaljiForma
     */
    public DetaljiForma() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1ID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1ID = new javax.swing.JTextField();
        jTextField2PREZIME = new javax.swing.JTextField();
        jTextField3EMAIL = new javax.swing.JTextField();
        jTextFieldIME = new javax.swing.JTextField();
        jComboBox1NIVOST = new javax.swing.JComboBox();
        jButton1omoguciIzmenu = new javax.swing.JButton();
        jButton1IZMENI = new javax.swing.JButton();
        jButton1OBRISI = new javax.swing.JButton();
        jButton1kreirajst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student forma");

        jLabel1ID.setText("ID studenta:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Nivo studija:");

        jTextField2PREZIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2PREZIMEActionPerformed(evt);
            }
        });

        jTextField3EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3EMAILActionPerformed(evt);
            }
        });

        jButton1omoguciIzmenu.setText("Omoguci izmenu");
        jButton1omoguciIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1omoguciIzmenuActionPerformed(evt);
            }
        });

        jButton1IZMENI.setText("Izmeni studenta");

        jButton1OBRISI.setText("Obrisi studenta");

        jButton1kreirajst.setText("Kreiraj studenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1kreirajst, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1ID)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1ID)
                            .addComponent(jTextField3EMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jTextField2PREZIME, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jTextFieldIME, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jComboBox1NIVOST, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1IZMENI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1OBRISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1omoguciIzmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1ID)
                    .addComponent(jTextField1ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1omoguciIzmenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1IZMENI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2PREZIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1OBRISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1NIVOST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1kreirajst)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3EMAILActionPerformed

    private void jTextField2PREZIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2PREZIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2PREZIMEActionPerformed

    private void jButton1omoguciIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1omoguciIzmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1omoguciIzmenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DetaljiForma().setVisible(true);
//            }
//        });
//    }

    public JButton getjButton1IZMENI() {
        return jButton1IZMENI;
    }

    public void setjButton1IZMENI(JButton jButton1IZMENI) {
        this.jButton1IZMENI = jButton1IZMENI;
    }

    public JButton getjButton1OBRISI() {
        return jButton1OBRISI;
    }

    public JButton getjButton1kreirajst() {
        return jButton1kreirajst;
    }

    public void setjButton1kreirajst(JButton jButton1kreirajst) {
        this.jButton1kreirajst = jButton1kreirajst;
    }

    public void setjButton1OBRISI(JButton jButton1OBRISI) {
        this.jButton1OBRISI = jButton1OBRISI;
    }

    public JButton getjButton1omoguciIzmenu() {
        return jButton1omoguciIzmenu;
    }

    public void setjButton1omoguciIzmenu(JButton jButton1omoguciIzmenu) {
        this.jButton1omoguciIzmenu = jButton1omoguciIzmenu;
    }

    public JComboBox getjComboBox1NIVOST() {
        return jComboBox1NIVOST;
    }

    public void setjComboBox1NIVOST(JComboBox jComboBox1NIVOST) {
        this.jComboBox1NIVOST = jComboBox1NIVOST;
    }

    public JTextField getjTextField1ID() {
        return jTextField1ID;
    }

    public void setjTextField1ID(JTextField jTextField1ID) {
        this.jTextField1ID = jTextField1ID;
    }

    public JTextField getjTextField2PREZIME() {
        return jTextField2PREZIME;
    }

    public void setjTextField2PREZIME(JTextField jTextField2PREZIME) {
        this.jTextField2PREZIME = jTextField2PREZIME;
    }

    public JTextField getjTextField3EMAIL() {
        return jTextField3EMAIL;
    }

    public void setjTextField3EMAIL(JTextField jTextField3EMAIL) {
        this.jTextField3EMAIL = jTextField3EMAIL;
    }

    public JTextField getjTextFieldIME() {
        return jTextFieldIME;
    }

    public void setjTextFieldIME(JTextField jTextFieldIME) {
        this.jTextFieldIME = jTextFieldIME;
    }

    public JLabel getjLabel1ID() {
        return jLabel1ID;
    }
    
    public void addBtnOmoguciIzmenuActionListener(ActionListener actionListener){
        jButton1omoguciIzmenu.addActionListener(actionListener);
    }
    public void addBtnPromeniActionListener(ActionListener actionListener){
        jButton1IZMENI.addActionListener(actionListener);
    }
    public void addBtnObrisiActionListener(ActionListener actionListener){
        jButton1OBRISI.addActionListener(actionListener);
    }
    public void addBtnKreirajActionListener(ActionListener actionListener){
        jButton1kreirajst.addActionListener(actionListener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1IZMENI;
    private javax.swing.JButton jButton1OBRISI;
    private javax.swing.JButton jButton1kreirajst;
    private javax.swing.JButton jButton1omoguciIzmenu;
    private javax.swing.JComboBox jComboBox1NIVOST;
    private javax.swing.JLabel jLabel1ID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1ID;
    private javax.swing.JTextField jTextField2PREZIME;
    private javax.swing.JTextField jTextField3EMAIL;
    private javax.swing.JTextField jTextFieldIME;
    // End of variables declaration//GEN-END:variables
}
