/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Bibliotekar;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2ULOGOVANI = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2kreirajIZN = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1kreiraj = new javax.swing.JMenuItem();
        jMenuItem2pretrazi = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2ubaciTD = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Univerzitetska biblioteka, FON");

        jLabel2ULOGOVANI.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2ULOGOVANI.setText("jLabel2");

        jMenu3.setText("Iznajmljivanje");

        jMenuItem2kreirajIZN.setText("Kreiraj");
        jMenuItem2kreirajIZN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2kreirajIZNActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2kreirajIZN);

        jMenuItem5.setText("Pretraži");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Student");

        jMenuItem1kreiraj.setText("Kreiraj");
        jMenuItem1kreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1kreirajActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1kreiraj);

        jMenuItem2pretrazi.setText("Pretraži");
        jMenuItem2pretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2pretraziActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2pretrazi);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Termin dežurstva");

        jMenuItem2ubaciTD.setText("Ubaci");
        jMenuItem2ubaciTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ubaciTDActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2ubaciTD);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2ULOGOVANI, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2ULOGOVANI)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1kreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1kreirajActionPerformed
        //koordinator.Koordinator.getInstance().otvoriKreirajIznajmljivanjeFormu();
    }//GEN-LAST:event_jMenuItem1kreirajActionPerformed

    private void jMenuItem2pretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2pretraziActionPerformed
        // TODO add your handling code here:
        koordinator.Koordinator.getInstance().otvoriPrikazStudenataFormu();
    }//GEN-LAST:event_jMenuItem2pretraziActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        koordinator.Koordinator.getInstance().otvoriPrikazIznajmljivanjaFormu();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2kreirajIZNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2kreirajIZNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2kreirajIZNActionPerformed

    private void jMenuItem2ubaciTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ubaciTDActionPerformed
        // TODO add your handling code here:
        koordinator.Koordinator.getInstance().otvoriUbaciTDFormu();
                
    }//GEN-LAST:event_jMenuItem2ubaciTDActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GlavnaForma().setVisible(true);
//            }
//        });
//    }

  
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GlavnaForma().setVisible(true);
//            }
//        });
//    }

    public JLabel getjLabel2ULOGOVANI() {
        return jLabel2ULOGOVANI;
    }

    
    public void setjLabel2ULOGOVANI(JLabel jLabel2ULOGOVANI) {
        this.jLabel2ULOGOVANI = jLabel2ULOGOVANI;
    }
    public void addJMenuKreirajActionListener(ActionListener actionListener){
        //klikom na menu item se rezervise red u tabeli baze
        jMenuItem1kreiraj.addActionListener(actionListener);
    }
    public void addJMenuKreirajIZNActionListener(ActionListener actionListener){
        //klikom na menu item se rezervise red u tabeli baze
        jMenuItem2kreirajIZN.addActionListener(actionListener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2ULOGOVANI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1kreiraj;
    private javax.swing.JMenuItem jMenuItem2kreirajIZN;
    private javax.swing.JMenuItem jMenuItem2pretrazi;
    private javax.swing.JMenuItem jMenuItem2ubaciTD;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
    
