/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class KreirajPromeniIznajmljivanjeForma extends javax.swing.JFrame {

    /**
     * Creates new form KreirajIznajmljivanjeForma
     */
    public KreirajPromeniIznajmljivanjeForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1datumIzn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1student = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1knjige = new javax.swing.JComboBox();
        jButton1dodajStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1stavke = new javax.swing.JTable();
        jButton1obrisiStavku = new javax.swing.JButton();
        jButton1unesiDatVr = new javax.swing.JButton();
        jButton1kreirajIzn = new javax.swing.JButton();
        jButton1promeni = new javax.swing.JButton();
        jButton1omoguci = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5id = new javax.swing.JLabel();
        jTextField1idIznajmljivanja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiraj iznajmljivanje");

        jLabel1.setText("Datum iznajmljivanja:");

        jLabel2.setText("Student:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavke iznajmljivanja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        jLabel3.setText("Knjiga:");

        jButton1dodajStavku.setText("Dodaj");

        jTable1stavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1stavke);

        jButton1obrisiStavku.setText("Ukloni");
        jButton1obrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1obrisiStavkuActionPerformed(evt);
            }
        });

        jButton1unesiDatVr.setText("Unesi datum vracanja");
        jButton1unesiDatVr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1unesiDatVrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBox1knjige, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1dodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1obrisiStavku)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1unesiDatVr))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1knjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1dodajStavku)
                    .addComponent(jButton1obrisiStavku)
                    .addComponent(jButton1unesiDatVr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1kreirajIzn.setText("Kreiraj iznajmljivanje");
        jButton1kreirajIzn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1kreirajIznActionPerformed(evt);
            }
        });

        jButton1promeni.setText("Izmeni");

        jButton1omoguci.setText("Omoguci izmenu podataka");

        jLabel4.setText("(dd.MM.yyyy)");

        jLabel5id.setText("ID:");

        jTextField1idIznajmljivanja.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1datumIzn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1student, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1idIznajmljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1promeni, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1omoguci)
                    .addComponent(jButton1kreirajIzn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5id))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1idIznajmljivanja)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1datumIzn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jButton1kreirajIzn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1omoguci, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1promeni, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1obrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1obrisiStavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1obrisiStavkuActionPerformed

    private void jButton1kreirajIznActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1kreirajIznActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1kreirajIznActionPerformed

    private void jButton1unesiDatVrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1unesiDatVrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1unesiDatVrActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KreirajPromeniIznajmljivanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KreirajPromeniIznajmljivanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KreirajPromeniIznajmljivanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KreirajPromeniIznajmljivanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KreirajPromeniIznajmljivanjeForma().setVisible(true);
//            }
//        });
//    }

    public JButton getjButton1dodajStavku() {
        return jButton1dodajStavku;
    }

    public JButton getjButton1kreirajIzn() {
        return jButton1kreirajIzn;
    }

    public JButton getjButton1obrisiStavku() {
        return jButton1obrisiStavku;
    }

    public JComboBox getjComboBox1knjige() {
        return jComboBox1knjige;
    }

    public JComboBox getjComboBox1student() {
        return jComboBox1student;
    }

    public JTable getjTable1stavke() {
        return jTable1stavke;
    }

    public JTextField getjTextField1datumIzn() {
        return jTextField1datumIzn;
    }

    public JLabel getjLabel5id() {
        return jLabel5id;
    }

    public JButton getjButton1omoguci() {
        return jButton1omoguci;
    }

    public JTextField getjTextField1idIznajmljivanja() {
        return jTextField1idIznajmljivanja;
    }

    public void setjTextField1idIznajmljivanja(JTextField jTextField1idIznajmljivanja) {
        this.jTextField1idIznajmljivanja = jTextField1idIznajmljivanja;
    }

    public void setjButton1omoguci(JButton jButton1omoguci) {
        this.jButton1omoguci = jButton1omoguci;
    }

    public JButton getjButton1promeni() {
        return jButton1promeni;
    }

    public void setjButton1promeni(JButton jButton1promeni) {
        this.jButton1promeni = jButton1promeni;
    }

    public JButton getjButton1unesiDatVr() {
        return jButton1unesiDatVr;
    }

    public void setjButton1unesiDatVr(JButton jButton1unesiDatVr) {
        this.jButton1unesiDatVr = jButton1unesiDatVr;
    }
    
    //KREIRAJ IZNAJMLJIVANJE
    public void addBtnKreirajIznActionListener(ActionListener actionListener){
        jButton1kreirajIzn.addActionListener(actionListener);
    }
    //ZA STAVKU-KNJIGU
    public void addBtnDodajKnjiguActionListener(ActionListener actionListener){
        jButton1dodajStavku.addActionListener(actionListener);
    }
    public void addBtnUkloniKnjiguActionListener(ActionListener actionListener){
        jButton1obrisiStavku.addActionListener(actionListener);
    }
    //PROMENI IZN
    public void addBtnPromeniIznActionListener(ActionListener actionListener){
        jButton1promeni.addActionListener(actionListener);
    }
    //OMOGUCI IZMENU
    public void addBtnOMOGUCIizmenuActionListener(ActionListener actionListener){
        jButton1omoguci.addActionListener(actionListener);
    }
    public void addBtnUnesiDatVrActionListener(ActionListener actionListener){
        jButton1unesiDatVr.addActionListener(actionListener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1dodajStavku;
    private javax.swing.JButton jButton1kreirajIzn;
    private javax.swing.JButton jButton1obrisiStavku;
    private javax.swing.JButton jButton1omoguci;
    private javax.swing.JButton jButton1promeni;
    private javax.swing.JButton jButton1unesiDatVr;
    private javax.swing.JComboBox jComboBox1knjige;
    private javax.swing.JComboBox jComboBox1student;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1stavke;
    private javax.swing.JTextField jTextField1datumIzn;
    private javax.swing.JTextField jTextField1idIznajmljivanja;
    // End of variables declaration//GEN-END:variables
}
